# Generated by Django 4.1.7 on 2023-09-18 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_user_date_joined_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='main_post',
            field=models.ForeignKey(default='Post deleted.', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='comments', to='network.post'),
        ),
    ]
