# Generated by Django 4.1.7 on 2023-09-19 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_comment_main_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_edited',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_likers',
        ),
    ]
