# Generated by Django 4.1.7 on 2023-09-19 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_remove_comment_comment_edited_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-commented']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_content',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_date',
            new_name='commented',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_poster',
            new_name='commenter',
        ),
    ]
